# [rust]
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
# workspace_dir = "."

# capsule version
version = "0.4.4 87bd895"
# path of deployment config file
deployment = "deployment.toml"

[[contracts]]
name = "sidechain-config-cell"
template_type = "Rust"
