[workspace]
members = [
  "tests",
  "contracts/always-success",
  "contracts/checker-bonding-lock",
  "contracts/sidechain-fee-lock",
  "contracts/sidechain-state-lock",
]

[profile.release]
overflow-checks = true
opt-level = 's'
lto = true
codegen-units = 1
panic = 'abort'
